services:
  mysql:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - /var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.12-rc-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 5s
      timeout: 20s
      retries: 5

  node:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notifications:
    build: .
    ports:
      - '3001:3001'
    volumes:
      - ./receiver:/app/receiver
    restart: always
    command: node receiver
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
